# Generated by Django 5.2.8 on 2025-12-02 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash_on_delivery', 'Cash on Delivery'), ('bkash', 'bKash'), ('credit_card', 'Credit Card')], max_length=30),
        ),
    ]
